service: defillama-nft

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  environment:
    stage: prod

package:
  individually: true

custom:
  tableName: prod-nft-table
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'npm'
    excludeFiles: src/**/*.test.ts

functions:
  triggerAdapters:
    handler: src/handlers/triggerAdapters.default
    events:
      - schedule: cron(0 * * * ? *)
  triggerAdapter:
    handler: src/handlers/triggerAdapter.default
    timeout: 900
    memorySize: 512
  getChains:
    handler: src/handlers/getChains.default
    events:
      - http:
          path: chains
          method: get
  getChart:
    handler: src/handlers/getChart.default
    events:
      - http:
          path: chart
          method: get
      - http:
          path: chart/chain/{chain}
          method: get
      - http:
          path: chart/marketplace/{marketplace}
          method: get
  getCollection:
    handler: src/handlers/getCollection.default
    events:
      - http:
          path: collection/{slug}
          method: get
  getCollections:
    handler: src/handlers/getCollections.default
    events:
      - http:
          path: collections
          method: get
      - http:
          path: collections/chain/{chain}
          method: get
      - http:
          path: collections/marketplace/{marketplace}
          method: get
  getMarketplaces:
    handler: src/handlers/getMarketplaces.default
    events:
      - http:
          path: marketplaces
          method: get

resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}

plugins:
  - serverless-webpack
  - serverless-offline
