Resources:
  DynamoTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain # Make sure the tables can't be deleted by CloudFormation/Serverless
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: category
          AttributeType: S
        - AttributeName: totalVolume
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: collectionsIndex
          KeySchema:
            - AttributeName: category
              KeyType: HASH
            - AttributeName: totalVolumeUSD
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - address
              - name
              - logo
              - totalVolume
              - totalVolumeUSD
              - dailyVolume
              - dailyVolumeUSD
              - floor
              - owners
              - chains
              - marketplaces
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
